baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Let's learn together..."
theme = "m10c"
paginate = 30

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  #[[menu.main]]
  #  identifier = "tags"
  #  name = "Tags"
  #  url = "/tags/"
  #  weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "David Morin"
  description = "Welcome digital traveler! I am always open to collaborate - email link below if you have any questions. E n J o Y!"
  menu_item_separator = " - "
  #[[params.social]]
  #  icon = "github"
  #  name = "Github"
  #  url = "https://github.com/gohugoio"
  #[[params.social]]
  #  icon = "twitter"
  #  name = "Twitter"
  #  url = "https://twitter.com/gohugoio"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/djmorin693/"
  [[params.social]]
    icon = "mail"
    name = "Email"
    url = "mailto:jjwattz693@gmail.com"
 

  # Default theme
  [params.style]
    darkestColor = "#242930"
    darkColor = "#353b43"
    lightColor = "#afbac4"
    lightestColor = "#ffffff"
    primaryColor = "#36A8F8"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"


